name: Publish reports

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('${{github.event.action}}');
            console.log(${{github.event.organization}});
            console.log(${{github.event.repository}});
            console.log(${{github.event.sender}});
            console.log(${{github.event.workflow_run.id}});
            console.log(${{github.event.workflow_run.head_sha}});
        
