name: Publish reports

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log(JSON.stringify);
            console.log(${{github.event}});
            var e = ${{github.event}};
            for(var s in e) {
              console.log(s + ' ' + e[s])
            };
            console.log(${{github.event.workflow_run.id}});
        
